[workspace]
members = [
    "crates/mpsgraph-rs",
    "crates/mpsgraph-tools-rs",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Eugene Bokhan <eugenebokhan@icloud.com>"]
repository = "https://github.com/computer-graphics-tools/mpsgraph-rs"